baseURL = "/access2justicePDX/"
fullURL = "//www.codeforportland.org/access2justicePDX/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Access2Justice"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = true
githubBaseURL = "https://github.com/CodeForPortland/access2justicePDX/tree/www-proposal/content/"
disqusShortname= "access2justice-1"

[params]
  editURL = "https://github.com/CodeForPortland/access2justicePDX/tree/www-proposal/content/"
  description = "The public face for Access2Justice."
  author = "Code4PDX"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Code4PDX presents Access2Justice"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "cp"
url = "https://github.com/CodeForPortland/access2justicePDX"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-server'></i> Status"
url = "/status"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Attributions"
url = "/attributions"
weight = 30